version: '2'

services:
    web:
      build:
        context: ./
        dockerfile: web.dockerfile
      volumes:
        - ./:/var/www
        - ./vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
     
    php:
        # image: php:8.0-fpm
        build: 
          context: ./
          dockerfile: Dockerfile
        volumes:
          - ./:/var/www
        
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'hhh'
            MYSQL_PASSWORD: 'root'
        volumes:
            - ./:/var/www
        ports:
            - 3306:3306

    phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_HOST=3306
        